#!/bin/bash

. /.initrd/initenv
. uevent-sh-functions
. initrd-sh-functions

DEVNAME="${DEVNAME#/dev}"
DEVNAME="${DEVNAME#/}"
DEVNAME="/dev/$DEVNAME"

[ "$DEVTYPE" = "disk" ] || exit 0
[ "$ID_SERIAL" = "$FLASH_SERIAL" ] || exit 0

event="$(make_event)"
environ -q > "$event"
echo "LOCKED_FLASH_ROOT_NUM='$((${FLASH_SERIAL: -1} + 1))'" >> "$event"
echo "LOCKED_FLASH_ROOT='$DEVNAME'" >> "$event"
release_event flash-unlock "$event"

exit 0
